```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Chart1.R")
source("Chart2.R")
source("Chart3.R")
source("summary.R")
```
--- 
title: "A3: SPL Library Checkouts"
output: html_document
---

### Introduction

Horizon and Overdrive are both system & services that allows you to view contents via a library. Both of these services are available for you to use at the Seattle public library (SPL). SPL allows you to still access material without having to go in person into the library itself to check it out. Just as how we have become more reliant on more digital applications to do school work, libraries can now also allow us to access content online. As the pandemic was not very long ago, and now that we are seeing a fast trend towards digital technology to access our information, I was curious as to the trends of the types of services most/ least used in SPL over the past several years. 


### Summary Information

Horizon was the main form of checkout medium while Freegal was the least used form of medium in 2018. Both Horizon and Overdrive had the most amounts of check outs in January. Below is a list of the top 10 most checked out titles in the past 5 years:

1) SPL HotSpot: connecting Seattle/ [distributed by T-mobile]
2) FlexTech --Laptop
3) Headphones/ Seattle Public Library 
4) Educated: A Memoir
5) Becoming (Unabridged)
6) Where the Crawdads Sing
7) So You Want to Talk about Race (Unabridged)
8) Becoming
9) In Building Device Checkout
10) The New Yorker

Which was the main form of checkout mediums, had the most usage in 2018?

`r top_medium``

Which was the main form of checkout mediums, had the least usage in 2018?

`r bot_medium`

Which month did Horizon have the most amount of check outs in total for the past 5 years? 

`r horizon_monthly_avg`

Which months did OverDrive have the most amount of check outs in total for the past 5 years?

`r OD_monthly_avg`

What are the top 10 most checked out 'Titles' of within the last 5 year?

`r top_10_most_checked_out`

### The Dataset

- Who collected/published the data?  

Seattle Public Library (SPL) 

- What are the parameters of the data (dates, number of checkouts, kinds of books, etc.)?

Publisher, publication year, creater, ISBN, title, subject, checkouts, checkout year & month & type, usage class, and material type

- How was the data collected or generated?  

When people check things out at Seattle Public liberary locations, it gets noted as data.

- Why was the data collected?  

To show the public what people like to use and to make sure people can access and view it (not withhold any information). It was also used to improve the performace of the libarary if the data was just out there for anyone to see- keeps them accountable 

- What, if any, ethical questions do you need to consider when working with this data?  

If the data from these people using the library was taken with their consent and knowlegde.

- What are possible limitations or problems with this data?   (at least 200 words)

Some variables did not have all the data filled in so when analyzing them, I was looking for something that had as much data as possible. The more data you have your hands on, the more accurate and the more it is describing the whole story more accurately. In terms of how far back we can go with this data, that is a limitation in and of itself because the technology wasn't as prominent or readily available to use for this type of platform (hence why we are more familiar with people back then going to the physical libraries to check things out). Due to this, we can only go back and have data for as long as the SPL library started to adopt this online/ digital system. This is not a problem in my case since it is more focused on recent years ever since the pandemic hit and the only way people could borrow media was online. Though, for those that are looking for data further back, the usage data would be handy. I wouldn't say that this was a major limitation because if technology was used a lot back then, there would be no use in collecting this type of data for them, but it would be for us nowadays to look at. 

- How many observations (rows) are in your data?
> 816354

### First Trends Over Time Chart

`r Chart1`

I included this chart because seeing the most and least popular type of medium used always is a good start to look into why people may like one form over another. The trend seen in this graph is that the most popular checkout types over the past 5 years is Horizon, while the least popular type is Freegal.

### Second Trends Over Time Chart

`r Chart2`

I included this chart because I wanted to see if the forms of medium changed in popularity depending on the month, or if there was a certain month that people just used these mediums more than others. The graph shows that the highest amounts of check outs for the top 2 most used mediums (Horizon and OverDrive) was in January.


### Your Choice

`r Chart3`

I wanted to include this chart because I wanted to see what the most popular titles are for checkouts as this may provide a clue as to who the main audience is. The graph shows that (roughly estimated most to least purely based on which bar looked higher than another), the top 10 titles in the past 5 years are: 

1) SPL HotSpot: connecting Seattle/ [distributed by T-mobile]
2) FlexTech --Laptop
3) Headphones/ Seattle Public Library 
4) Educated: A Memoir
5) Becoming (Unabridged)
6) Where the Crawdads Sing
7) So You Want to Talk about Race (Unabridged)
8) Becoming
9) In Building Device Checkout
10) The New Yorker
